/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Returns the current owner's saved business information, content rules, and posting preferences.
 * @summary Get the current business profile
 */
export const GetBusinessProfileResponse = zod.object({
  "userId": zod.string(),
  "businessId": zod.string(),
  "businessName": zod.string(),
  "businessType": zod.string(),
  "address": zod.string(),
  "cityState": zod.string(),
  "phone": zod.string(),
  "website": zod.string(),
  "description": zod.string(),
  "services": zod.array(zod.string()),
  "products": zod.array(zod.string()),
  "hours": zod.string(),
  "promotions": zod.string(),
  "targetCustomers": zod.string(),
  "tone": zod.string(),
  "alwaysMention": zod.array(zod.string()),
  "neverMention": zod.array(zod.string()),
  "postingFrequency": zod.union([zod.literal(10),zod.literal(20),zod.literal(30)]),
  "approvalMode": zod.enum(['approval', 'confirmation', 'auto']),
  "updatedAt": zod.coerce.date()
})


/**
 * Replaces the current owner's saved business information, content rules, and posting preferences.
 * @summary Save the current business profile
 */
export const UpdateBusinessProfileBody = zod.object({
  "businessName": zod.string(),
  "businessType": zod.string(),
  "address": zod.string(),
  "cityState": zod.string(),
  "phone": zod.string(),
  "website": zod.string(),
  "description": zod.string(),
  "services": zod.array(zod.string()),
  "products": zod.array(zod.string()),
  "hours": zod.string(),
  "promotions": zod.string(),
  "targetCustomers": zod.string(),
  "tone": zod.string(),
  "alwaysMention": zod.array(zod.string()),
  "neverMention": zod.array(zod.string()),
  "postingFrequency": zod.union([zod.literal(10),zod.literal(20),zod.literal(30)]),
  "approvalMode": zod.enum(['approval', 'confirmation', 'auto'])
})

export const UpdateBusinessProfileResponse = zod.object({
  "userId": zod.string(),
  "businessId": zod.string(),
  "businessName": zod.string(),
  "businessType": zod.string(),
  "address": zod.string(),
  "cityState": zod.string(),
  "phone": zod.string(),
  "website": zod.string(),
  "description": zod.string(),
  "services": zod.array(zod.string()),
  "products": zod.array(zod.string()),
  "hours": zod.string(),
  "promotions": zod.string(),
  "targetCustomers": zod.string(),
  "tone": zod.string(),
  "alwaysMention": zod.array(zod.string()),
  "neverMention": zod.array(zod.string()),
  "postingFrequency": zod.union([zod.literal(10),zod.literal(20),zod.literal(30)]),
  "approvalMode": zod.enum(['approval', 'confirmation', 'auto']),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary List the current owner's posts
 */
export const GetPostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
}))
})


/**
 * @summary Generate and save social posts
 */
export const GeneratePostsBody = zod.object({
  "count": zod.union([zod.literal(10),zod.literal(20),zod.literal(30)]),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['all', 'service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "tone": zod.string().optional(),
  "campaign": zod.string().optional()
})

export const GeneratePostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
})),
  "source": zod.enum(['ai', 'fallback']),
  "qualitySummary": zod.object({
  "passed": zod.number().int(),
  "needsReview": zod.number().int()
})
})


/**
 * @summary Approve all reviewable posts
 */
export const ApproveAllPostsResponse = zod.object({
  "posts": zod.array(zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
}))
})


/**
 * @summary Edit a saved post
 */
export const UpdatePostParams = zod.object({
  "postId": zod.coerce.string()
})

export const UpdatePostBody = zod.object({
  "content": zod.string().optional(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']).optional(),
  "scheduledAt": zod.coerce.date().nullish()
})

export const UpdatePostResponse = zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
})


/**
 * @summary Delete a saved post
 */
export const DeletePostParams = zod.object({
  "postId": zod.coerce.string()
})

export const DeletePostResponse = zod.void()


/**
 * @summary Regenerate one saved post
 */
export const RegeneratePostParams = zod.object({
  "postId": zod.coerce.string()
})

export const RegeneratePostResponse = zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
})


/**
 * @summary Approve one post for scheduling
 */
export const ApprovePostParams = zod.object({
  "postId": zod.coerce.string()
})

export const ApprovePostResponse = zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
})


/**
 * @summary Reject one post
 */
export const RejectPostParams = zod.object({
  "postId": zod.coerce.string()
})

export const RejectPostResponse = zod.object({
  "id": zod.string(),
  "businessId": zod.string(),
  "content": zod.string(),
  "platform": zod.enum(['facebook', 'instagram', 'google_business_profile', 'general']),
  "category": zod.enum(['service_spotlight', 'educational_tip', 'seasonal', 'problem_solution', 'business_introduction', 'product_spotlight', 'promotion_announcement', 'faq', 'engagement', 'local_community']),
  "status": zod.enum(['draft', 'needs_approval', 'approved', 'scheduled', 'published', 'rejected']),
  "createdAt": zod.coerce.date(),
  "scheduledAt": zod.coerce.date().nullable(),
  "approvalDate": zod.coerce.date().nullable(),
  "publishedAt": zod.coerce.date().nullable(),
  "generationSource": zod.enum(['ai', 'fallback', 'manual']),
  "generationContext": zod.record(zod.string(), zod.unknown()),
  "qualityStatus": zod.enum(['pass', 'review']),
  "qualityIssues": zod.array(zod.string())
})


