/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessProfileApprovalMode } from './businessProfileApprovalMode';
import type { BusinessProfilePostingFrequency } from './businessProfilePostingFrequency';

export interface BusinessProfile {
  userId: string;
  businessId: string;
  businessName: string;
  businessType: string;
  address: string;
  cityState: string;
  phone: string;
  website: string;
  description: string;
  services: string[];
  products: string[];
  hours: string;
  promotions: string;
  targetCustomers: string;
  tone: string;
  alwaysMention: string[];
  neverMention: string[];
  postingFrequency: BusinessProfilePostingFrequency;
  approvalMode: BusinessProfileApprovalMode;
  updatedAt: Date;
}
