/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type BusinessProfileApprovalMode = typeof BusinessProfileApprovalMode[keyof typeof BusinessProfileApprovalMode];


export const BusinessProfileApprovalMode = {
  approval: 'approval',
  confirmation: 'confirmation',
  auto: 'auto',
} as const;
