/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessProfileInputApprovalMode } from './businessProfileInputApprovalMode';
import type { BusinessProfileInputPostingFrequency } from './businessProfileInputPostingFrequency';

export interface BusinessProfileInput {
  businessName: string;
  businessType: string;
  address: string;
  cityState: string;
  phone: string;
  website: string;
  description: string;
  services: string[];
  products: string[];
  hours: string;
  promotions: string;
  targetCustomers: string;
  tone: string;
  alwaysMention: string[];
  neverMention: string[];
  postingFrequency: BusinessProfileInputPostingFrequency;
  approvalMode: BusinessProfileInputApprovalMode;
}
