/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type BusinessProfileInputPostingFrequency = typeof BusinessProfileInputPostingFrequency[keyof typeof BusinessProfileInputPostingFrequency];


export const BusinessProfileInputPostingFrequency = {
  NUMBER_10: 10,
  NUMBER_20: 20,
  NUMBER_30: 30,
} as const;
