/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostQualityStatus = typeof PostQualityStatus[keyof typeof PostQualityStatus];
export declare const PostQualityStatus: {
    readonly pass: "pass";
    readonly review: "review";
};
//# sourceMappingURL=postQualityStatus.d.ts.map