/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostGenerationInputPlatform = typeof PostGenerationInputPlatform[keyof typeof PostGenerationInputPlatform];


export const PostGenerationInputPlatform = {
  facebook: 'facebook',
  instagram: 'instagram',
  google_business_profile: 'google_business_profile',
  general: 'general',
} as const;
