/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PostCategory } from './postCategory';
import type { PostGenerationContext } from './postGenerationContext';
import type { PostGenerationSource } from './postGenerationSource';
import type { PostPlatform } from './postPlatform';
import type { PostQualityStatus } from './postQualityStatus';
import type { PostStatus } from './postStatus';

export interface Post {
  id: string;
  businessId: string;
  content: string;
  platform: PostPlatform;
  category: PostCategory;
  status: PostStatus;
  createdAt: Date;
  scheduledAt: Date | null;
  approvalDate: Date | null;
  publishedAt: Date | null;
  generationSource: PostGenerationSource;
  generationContext: PostGenerationContext;
  qualityStatus: PostQualityStatus;
  qualityIssues: string[];
}
