/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Post } from './post';
import type { PostGenerationResponseQualitySummary } from './postGenerationResponseQualitySummary';
import type { PostGenerationResponseSource } from './postGenerationResponseSource';

export interface PostGenerationResponse {
  posts: Post[];
  source: PostGenerationResponseSource;
  qualitySummary: PostGenerationResponseQualitySummary;
}
