/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostGenerationSource = typeof PostGenerationSource[keyof typeof PostGenerationSource];


export const PostGenerationSource = {
  ai: 'ai',
  fallback: 'fallback',
  manual: 'manual',
} as const;
