/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostGenerationSource = typeof PostGenerationSource[keyof typeof PostGenerationSource];
export declare const PostGenerationSource: {
    readonly ai: "ai";
    readonly fallback: "fallback";
    readonly manual: "manual";
};
//# sourceMappingURL=postGenerationSource.d.ts.map