/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostGenerationInputCount = typeof PostGenerationInputCount[keyof typeof PostGenerationInputCount];
export declare const PostGenerationInputCount: {
    readonly NUMBER_10: 10;
    readonly NUMBER_20: 20;
    readonly NUMBER_30: 30;
};
//# sourceMappingURL=postGenerationInputCount.d.ts.map