/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostGenerationInputCount = typeof PostGenerationInputCount[keyof typeof PostGenerationInputCount];


export const PostGenerationInputCount = {
  NUMBER_10: 10,
  NUMBER_20: 20,
  NUMBER_30: 30,
} as const;
