/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostGenerationInputCategory = typeof PostGenerationInputCategory[keyof typeof PostGenerationInputCategory];


export const PostGenerationInputCategory = {
  all: 'all',
  service_spotlight: 'service_spotlight',
  educational_tip: 'educational_tip',
  seasonal: 'seasonal',
  problem_solution: 'problem_solution',
  business_introduction: 'business_introduction',
  product_spotlight: 'product_spotlight',
  promotion_announcement: 'promotion_announcement',
  faq: 'faq',
  engagement: 'engagement',
  local_community: 'local_community',
} as const;
