/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostGenerationInputPlatform = typeof PostGenerationInputPlatform[keyof typeof PostGenerationInputPlatform];
export declare const PostGenerationInputPlatform: {
    readonly facebook: "facebook";
    readonly instagram: "instagram";
    readonly google_business_profile: "google_business_profile";
    readonly general: "general";
};
//# sourceMappingURL=postGenerationInputPlatform.d.ts.map