/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostQualityStatus = typeof PostQualityStatus[keyof typeof PostQualityStatus];


export const PostQualityStatus = {
  pass: 'pass',
  review: 'review',
} as const;
