/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostStatus = typeof PostStatus[keyof typeof PostStatus];
export declare const PostStatus: {
    readonly draft: "draft";
    readonly needs_approval: "needs_approval";
    readonly approved: "approved";
    readonly scheduled: "scheduled";
    readonly published: "published";
    readonly rejected: "rejected";
};
//# sourceMappingURL=postStatus.d.ts.map