/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostPlatform = typeof PostPlatform[keyof typeof PostPlatform];
export declare const PostPlatform: {
    readonly facebook: "facebook";
    readonly instagram: "instagram";
    readonly google_business_profile: "google_business_profile";
    readonly general: "general";
};
//# sourceMappingURL=postPlatform.d.ts.map