/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostStatus = typeof PostStatus[keyof typeof PostStatus];


export const PostStatus = {
  draft: 'draft',
  needs_approval: 'needs_approval',
  approved: 'approved',
  scheduled: 'scheduled',
  published: 'published',
  rejected: 'rejected',
} as const;
