/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostGenerationContext = {
    [key: string]: unknown;
};
//# sourceMappingURL=postGenerationContext.d.ts.map