/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type PostGenerationInputCategory = typeof PostGenerationInputCategory[keyof typeof PostGenerationInputCategory];
export declare const PostGenerationInputCategory: {
    readonly all: "all";
    readonly service_spotlight: "service_spotlight";
    readonly educational_tip: "educational_tip";
    readonly seasonal: "seasonal";
    readonly problem_solution: "problem_solution";
    readonly business_introduction: "business_introduction";
    readonly product_spotlight: "product_spotlight";
    readonly promotion_announcement: "promotion_announcement";
    readonly faq: "faq";
    readonly engagement: "engagement";
    readonly local_community: "local_community";
};
//# sourceMappingURL=postGenerationInputCategory.d.ts.map