/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PostUpdateInputPlatform } from './postUpdateInputPlatform';
export interface PostUpdateInput {
    content?: string;
    platform?: PostUpdateInputPlatform;
    scheduledAt?: Date | null;
}
//# sourceMappingURL=postUpdateInput.d.ts.map