/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type PostGenerationResponseSource = typeof PostGenerationResponseSource[keyof typeof PostGenerationResponseSource];


export const PostGenerationResponseSource = {
  ai: 'ai',
  fallback: 'fallback',
} as const;
