/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PostGenerationInputCategory } from './postGenerationInputCategory';
import type { PostGenerationInputCount } from './postGenerationInputCount';
import type { PostGenerationInputPlatform } from './postGenerationInputPlatform';
export interface PostGenerationInput {
    count: PostGenerationInputCount;
    platform: PostGenerationInputPlatform;
    category: PostGenerationInputCategory;
    tone?: string;
    campaign?: string;
}
//# sourceMappingURL=postGenerationInput.d.ts.map